# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='meal',
            field=models.CharField(choices=[('grub', 'GRUB'), ('lunch', 'LUNCH'), ('dinner', 'DINNER'), ('breakfast', 'BREAKFAST')], max_length=30),
        ),
    ]
