# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20170330_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='day',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
