# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 10:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_meal_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='meal',
            new_name='meal_type',
        ),
        migrations.AlterField(
            model_name='items',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Meal'),
        ),
    ]
