# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20170330_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Meal'),
        ),
    ]
